### ISSUE TITLE
 from dataloaders.helpers import *

### ISSUE THREAD

**Issue by jiaruHithub** [carrierlxk/AGNN#5]
when I run the code,it tells me that" ModuleNotFoundError: No module named 'dataloaders.helpers".then i looked for the dataloaders foder and i can't found file named 'helpers'.can you tell me why?

**Comment by carrierlxk** [comment]
You can just comment this line.

**Comment by jiaruHithub** [comment]
你好刘先生，我直接与您中文对话了，在您的模型中，我使用的是DAVIS-2016数据集，我不知道如何组织该数据集的目录，并且我在该数据集中没有找到val_seqs.txt文件，我该如何做呢？



















At 2020-03-23 18:46:29, "Lu Xiankai" <notifications@github.com> wrote:

You can just comment this line.

**Comment by carrierlxk** [comment]
blackswan
bmx-trees
breakdance
camel
car-roundabout
car-shadow
cows
dance-twirl
dog
drift-chicane
drift-straight
goat
horsejump-high
kite-surf
libby
motocross-jump
paragliding-launch
parkour
scooter-black
soapbox
